#---------------- Chaincode Deployment ---------------------
# CC_ID Package ID: marbles:2d798793d8683da47f22ce9f4ef288b094cc8dbdb337dc890a66173fb460dfc3
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode
  namespace: peers
  labels:
    app: chaincode
spec:
  selector:
    matchLabels:
      app: chaincode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode
    spec:
      containers:
        - image: docker.io/varshapichandi30/chaincode:1.0 #mention the image name
          name: chaincode
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_ID
              value: "marbles:0e32bb3d8967c238a1cd9008fdd97c50b937b255dea6684a46c4cbcd21fdfa8f" 
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7051"
          ports:
            - containerPort: 7051
